tasks:
  - name: Rust nightly
    before: |
      rustup toolchain install nightly
      rustup default nightly
      rustup component add rust-src --toolchain nightly
      rustup component add rustfmt
    init: |
      cargo build
      cargo test --no-run
